print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 % 4)
print(3 / 4)
print(3 ** 4)
print(3 // 4)

print('Phani')
print("Alapati")
print("India")
print("I am enjoying 30 Days of pyhton Challenge")

print(type(10))
print(type(8.90))
print(type(3.14))
print(type(4-4j))
print(type(['Phani', "Python", 'India']))
print(type('phani'))
print(type('Alapati'))
print(type('india'))